### ISSUE TITLE
Links and backlinks don't refresh when a document loads through a page link.

### ISSUE THREAD

**Issue by alexk7110** [brufdev/many-notes#35]
The document links and backlinks refresh correctly if you choose to load a document by clicking on its name at the tree view.
They don't seem to refresh if you visit a document by clicking a link of it on another document.

Version 0.8.0

**Comment by brufdev** [comment]
Good catch! I did a few more tests and noticed that the panel was not refreshing when closing files either. I just released a new version (v0.8.1) with both issues fixed. Thank you!

**Comment by alexk7110** [comment]
Works like a charm.

**Comment by v2kiran** [comment]
this is still happening by the way-using the latest release.
what solved it for me was not clicking on the tree-view but to add a tag, it seems without tags the backlinks dont become visible.
Also creating backlinks needs to be easier that what it is right now. We should be able to copy paths from the tree view and paste them

**Comment by brufdev** [comment]
> this is still happening by the way-using the latest release. what solved it for me was not clicking on the tree-view but to add a tag, it seems without tags the backlinks dont become visible.

I'm rewriting the entire frontend for the next version. The tree view component is mostly complete and will offer better performance, an active state for opened files, drag-and-drop node moving, and improved UI/UX. I’ll also look into this issue for the next version.

> Also creating backlinks needs to be easier that what it is right now. We should be able to copy paths from the tree view and paste them

This could be a good QoL improvement, but I need to confirm if it's doable when migrating the editor.

**Comment by v2kiran** [comment]
great to hear that and thank you for responding to a closed thread!
